### ISSUE TITLE
Recherche: écrire "Java" devrait faire ressortir les profils "Java" avant les profils "JavaScript"

### ISSUE THREAD

**Issue by yann-yinn** [popcorn-nantes/popcorn-nantes#148]
L'algo de recherche est largement améliorable, il est ici : https://github.com/popcorn-nantes/popcorn-nantes/blob/master/static/search.js

Il se base sur l'index de recherche ici présent une fois le site compilé:https://raw.githubusercontent.com/popcorn-nantes/popcorn-nantes.github.io/master/api/search-index.json

**Comment by yann-yinn** [comment]
Normal: les profils sont triés aléatoirement au build. La recherche ne fait que "masquer" les profils qui ne correspondent pas, l'ordre des résultats est donc aléatoire aussi...

**Comment by achorein** [comment]
J'ai fait une PR avec une proposition de fix, à discuter tout de même niveau perf mais nous n'avons pas non plus 10 000 profils :smile:
