### ISSUE TITLE
Le nom et le prénom sont inversés sur la modale de contact d'un profil

### ISSUE THREAD

**Issue by yann-yinn** [popcorn-nantes/popcorn-nantes#38]
dans `components/Person.vue`

<img width="1186" alt="capture d ecran 2019-01-02 a 15 34 30" src="https://user-images.githubusercontent.com/335495/50596314-174f2900-0ea4-11e9-9e95-97fb1dc2fdb4.png">

**Comment by fabienjuif** [comment]
J'adore tes flèches @yann-yinn :)

**Comment by yann-yinn** [comment]
héhé t'as vu ce sens de la pédagogie
