### ISSUE TITLE
License MIT

### ISSUE THREAD

**Issue by auggod** [popcorn-nantes/popcorn-nantes#44]
> On veut bien que des gens puissent tout simplement forker ce dépôt pour créer leur propre annuaire

Dans ce cas, je propose d'inclure la license MIT pour permettre à d'autres freelances dans le monde de forker votre repo.

**Comment by yann-yinn** [comment]
c'est fait, merci pour la PR !

**Comment by yann-yinn** [comment]
Salut ! pour info je l'ai retiré pour le moment car j'ai un doute pour la raison suivante : le code source contient actuellement les données concernant les profils des devs et la licence MIT inclut que le code source peut être utilisé y compris à des fins commerciales; ce qui sous-entend sauf erreur ma part que du coup que les données des profils peuvent être utilisées à des fins commerciales. Dans l'idée il faudrait séparer le repo qui reçoit les PR de contenus du code sources lui même pour rendre code plus réutilisable et résoudre ce point.

**Comment by fabienjuif** [comment]
Ce qui se fait parfois c'est de pinger tous les contributeurs (ici tous les frees) pour leur demander une validation écrite (dans une issue). avant de changer la license (ici en donner une)

**Comment by Hydrog3n** [comment]
@yann-yinn Tu pense qu'il serait possible de séparer les datas du code ? 

Une ça permettrais de créer d'autre popcorn mais continuer à développer le système.
Deux ça éviterait ce soucis de licence car dans un autre repo avec une licence spécifique.

**Comment by yann-yinn** [comment]
Hello ! Oui, il serait possible de faire en sorte que https://github.com/popcorn-nantes/popcorn-nantes ne contiennent que les contenus du site + medias, et mettre le code source du "moteur" sur un autre repo. A voir la manière la plus astucieux de "fusionner" les deux ensuite pour le build et la rédaction de contenu, peut être tout simplement un sous-module git.

Mais ça fait pas mal de taf pour un truc qui ne pose pas vraiment problème à ce jour je dirai ...

**Comment by Hydrog3n** [comment]
J'ai pas du tout réfléchi à comment faire c'était juste une idée. C'est bien vrai que ça cause pas mal de problème. 

Le git submodule serait ok pour la licence mais pour différencier les contents ça marcherais pas. ;)

**Comment by yann-yinn** [comment]
Ha oui, les "submodules" font partie de la conf du repo git; donc c'est plus décorellé, c'est ça (jamais bossé avec les submodules) ? 

Sinon en mode bricolage y'a l'option manuelle de cloner manuellement le dossier `content` (les datas) depuis un repo qui contient que ça; et d'ignorer ce répertoire `content` par défaut dans le repo git qui contient le code métier.

**Comment by fabienjuif** [comment]
Le plus simple / sérieux serait, je pense, de déclarer des `bin` dans ton `package.json` (start/build/etc) 

Tu en fais une dépendances, et les autres surcharges leur scripts

Exemple de projet utilisateur : 
```json
{
  "name": "popcorn-nantes",
  "scripts": {
    "start": "popcorn start"
  },
  "dependencies": {
     "popcorn": "^1.0.0"
  }
}
```

Et dans `popcorn` tu va cherche en fonction du `PWD` les fichiers markdown.


---

A l'instar de `create-react-app` et son `react-scripts`.

**Comment by yann-yinn** [comment]
En effet c'est le mieux sans être plus compliqué à mettre en place.

**Comment by fabienjuif** [comment]
J'esssaie de regarde ce w-e si ça vous dit

**Comment by yann-yinn** [comment]
Avec plaisir si tu es chaud. Est ce que je te crée dans l'organisation un repo "popcorn" qui contiendra uniquement le code du package npm  de popcorn ?

**Comment by fabienjuif** [comment]
Yes ok :)
Si tu peux m'inviter aussi dessus ce serait cool
Et je me ferais un repo `popcorn-test` avec mes propres markdown pour tester 👍

**Comment by yann-yinn** [comment]
Ok, c'est fait. Pour info les fichiers markdowns sont compilés en JSON via le module custom `nuxt-gustave` : il s'occupe de faire tourner les scripts du dossier `compilers` quand on démarre le serveur de dev, quand un fichier change et au build. Les compilers à faire tourner sont déclarés explicitement dans le fichier `nuxt.config.js`

**Comment by yann-yinn** [comment]
Il faudra trouver un nom pour le package `npm`, évidemment `popcorn` est déjà pris ^^.
Je suggère `popcorn-machine` ("Machine à Popcon"), puisque ça sera un peu une machine à faire des popcorns

**Comment by fabienjuif** [comment]
Ok, merci pour les infos, pour le nom ça me semble ok, mais je suis jamais très inspiré pour le nom de mes libs :p

**Comment by yann-yinn** [comment]
Les avantages de cette séparation sont nombreux, en dehors de la licence:
- Les développements sur _popcorn-machine_ n'impacteront pas la stabilité du site comme c'est le cas aujourd'hui en cas d'erreur (les PR de dev cotoient les PR de contribution)
- Les PR de contenus seront facile à distinguer de PR de dev ( ça rend en passant plus visibles ceux / celles qui contribuent à _popcorn-machine_ )
- Ca facilitera l'automatisation complète du déploiement si une PR de profil est acceptée

**Comment by fabienjuif** [comment]
@yann-yinn je clos, tu peux réouvrir si tu penses que c'est prématuré.
On a la même issue sur popcorn-machine.
