### ISSUE TITLE
Dissocier popcorn-nantes du moteur (popcorn-machine)

### ISSUE THREAD

**Issue by fabienjuif** [popcorn-nantes/popcorn-nantes#54]

**Comment by Hydrog3n** [comment]
Je tiens à dire bravo :clap:

**Comment by yann-yinn** [comment]
Ok, c'est bien `popcorn-machine` qui fait tourner `popcorn-nantes` depuis tout de suite 🎉 . La dissociation est ok, même si il y a quelques améliorations possibles. Il faudrait s'occuper cette issue pour qu'il soit possible de générer les fichiers nécessaires à un popcorn: https://github.com/popcorn-nantes/popcorn-machine/issues/14
