### ISSUE TITLE
Pourquoi popcorn ?

### ISSUE THREAD

**Issue by fabienjuif** [popcorn-nantes/popcorn-nantes#8]
Question con que je me pose :)

**Comment by yann-yinn** [comment]
Parce que je trouvais ça marrant , pas prise de tête et facile à retenir.
C'est aussi pour refléter l'idée qu'une des idées principales est que le site doit rester le plus léger et facile à maintenir possible; et qu'il soit possible de le forker pour créer son propre annuaire en deux secondes. (comme des ptits popcorn qui explosent partout )

**Comment by fabienjuif** [comment]
Alright merci :)
