### ISSUE TITLE
Capitalisation bon plans : vos meilleurs espaces de coworking à Nantes 

### ISSUE THREAD

**Issue by yann-yinn** [popcorn-nantes/popcorn-nantes#99]
Faites part des endroits où vous travaillez à Nantes en tant que dev free, essayez d'ajouter le plus gros avantage et inconvénient du lieu selon vous si vous avez le temps. Après je ferai une page au propre quelque part pour compiler tout ça (sur le site ?)

**Comment by yann-yinn** [comment]
en fait je vais plutôt faire une google spreadsheet

**Comment by 7h47** [comment]
Un fichier libre-office poussé sur le repo pourrait être bien ? histoire de rester dans l'open-source.
